accounts/urls.py
from django.urls import path, include

from accounts.views import user_profile, signup_profile, signout_user

urlpatterns = (
    path('', include('django.contrib.auth.urls')),
    path('profile/', user_profile, name='current user profile'),
    path('profile/<int:pk>/', user_profile, name='user profile'),
    path('signup/', signup_profile, name='signup profile'),
    path('signout/', signout_user, name='signout user'),
)

adventr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('feed/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path

from app.views import index

urlpatterns = [
    path('', index, name='index'),
]

posts/urls.py
from django.urls import path

from posts.views import feed, post_likes, post_comments, post_delete, post_edit, add_photo

urlpatterns = [
    path('', feed, name='feed'),
    path('likes/<int:pk>/', post_likes, name='post like'),
    path('comments/<int:pk>/', post_comments, name='post comments'),
    path('edit/<int:pk>/', post_edit, name='post edit'),
    path('delete/<int:pk>/', post_delete, name='post delete'),
    path('add/', add_photo, name='add photo'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    profile_picture = models.ImageField(upload_to='users', blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

app/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

from accounts.models import UserProfile


class Post(models.Model):
    location = models.CharField(max_length=20, blank=False)
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='posts',
    )

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}, {self.location}, {self.description}'


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

accounts/forms/signup_form.py
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

posts/forms/comment_form.py
from django import forms

from posts.models import Comment


class CommentForm(forms.Form):

    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':
                    'form-control rounded-2',
            }
        )
    )

posts/forms/photo_add_form.py
from django import forms
from posts.models import Post


class AddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = '__all__'

posts/forms/post_edit_form.py
from django import forms
from posts.models import Post


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('location', 'description')

        widgets = {
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.forms.signup_form import SignupForm
from accounts.models import UserProfile


def user_profile(request, pk=None):
    user = request.user if pk is None else User.objects.get(pk=pk)
    if request.method == 'GET':
        context = {
            'profile_user': user,
            'profile': user.userprofile,
            'posts': user.userprofile.post_set.all(),
        }

        return render(request, 'accounts/profile.html', context)


def signup_profile(request):
    if request.method == 'GET':
        context = {
            'form': SignupForm(),
        }

        return render(request, 'accounts/signup.html', context)
    else:
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = UserProfile(
                user=user
            )
            profile.save()
            login(request, user)
            return redirect('feed')

        context = {
            'form': form,
        }

        return render(request, 'accounts/signup.html', context)


def signout_user(request):
    logout(request)
    return redirect('index')

app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from posts.forms.comment_form import CommentForm
from posts.forms.photo_add_form import AddForm
from posts.forms.post_edit_form import EditForm
from posts.models import Post, Like, Comment


@login_required()
def feed(request):
    context = {
        'posts': Post.objects.all(),
    }

    return render(request, 'posts/feed.html', context)


@login_required()
def post_likes(request, pk):
    like = Like.objects.filter(user_id=request.user.userprofile.id, post_id=pk).first()
    if like:
        like.delete()
    else:
        post = Post.objects.get(pk=pk)
        like = Like(user=request.user.userprofile)
        like.post = post
        like.save()
    return redirect('feed')


@login_required()
def post_comments(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "GET":
        context = {
            'post': post,
            'form': CommentForm(),
        }

        return render(request, 'posts/comment-page.html', context)
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(comment=form.cleaned_data['comment'])
            comment.post = post
            comment.save()
            return redirect('post comments', pk)

        context = {
            'post': post,
            'form': form,
        }

        return render(request, 'posts/comment-page.html', context)


@login_required
def add_photo(request):
    post = Post()
    if request.method == 'GET':
        form = AddForm()

        context = {
            'form': form,
        }

        return render(request, 'posts/add-photo.html', context)

    else:
        form = AddForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('feed')

        context = {
            'form': form,
        }

        return render(request, 'posts/add-photo.html', context)


@login_required()
def post_edit(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'GET':
        form = EditForm(instance=post)

        context = {
            'form': form,
            'post': post,
        }

        return render(request, 'posts/post-edit.html', context)

    else:
        form = EditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('feed')

        context = {
            'form': form,
            'post': post,
        }

        return render(request, 'posts/post-edit.html', context)


@login_required()
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    img = post.image
    if request.method == "GET":
        context = {
            'post': post
        }

        return render(request, 'posts/post-delete.html', context)
    else:
        img.delete()
        post.delete()
        return redirect('feed')

templates/accounts/profile.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="text-center">
        <h1>Hello, {{ profile_user.username }}!</h1>
    </div>
    {% if posts %}
    <h2 class='text-center'>Posts</h2>
    <div class="row">
        <div class="row">
            {% for post in posts %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'post comments' post.pk %}" class="btn btn-primary">Comments</a>
                        Likes: {{ post.like_set.count }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="text-center">
        <h2>No posts yet.</h2>
        <a href="{% url 'add photo' %}" class="button btn">Add a photo</a>
    </div>
    {% endif %}
{% endblock %}

templates/accounts/signup.html
{% extends 'shared/site.html' %}
{% block site_content %}

    <div class="container-fluid" style="background-image: none">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post">
                    <h2>Sign up</h2>
                    {{ form }}
                    {% csrf_token %}
                    <button class="button btn btn-primary" type="submit">Sign up</button>
                    <span>Have an account?<a href="url to login" style="color:lightcoral">Sign in here</a></span>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'shared/site.html' %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/img_index.css' %}">
{% endblock %}


{% block site_title %}
    Adventr
{% endblock %}
{% block site_content %}
    <section class="index-center">
        <h1 class="list-item">SHARE YOUR BEST MOMENTS WITH FRIENDS</h1>
        <div>
            <div>
                <a href="{% url 'signup profile' %}" class="button btn btn-primary" type="submit">Sign up</a>
            </div>
            <div>
                Already have an account?
                <a href="{% url 'login' %}" style="color:lightcoral">Sign in</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/partials/nav.html
<header>
    <nav class="site-nav">
        <ul class="list-horizontal">
            <li class="list-item">
                <a href="{% url 'index' %}">
                    Home
                </a>
            </li>
            <li class="list-item">
                <a href="{% url 'feed' %}">
                    Feed
                </a>
            </li>
            <li class="list-item">
                <a href="{% url 'add photo' %}">
                    Add photo
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="list-item">
                    <a href="{% url 'user profile' user.id %}">
                        {{ user.username }}
                    </a>
                </li>
                <li class="list-item">
                    <a href="{% url 'signout user'%}">
                        Sign out
                    </a>
                </li>
            {% else %}
                <li class="list-item">
                    <a href="{% url 'login' %}">
                        Sign in
                    </a>
                </li>
                <li class="list-item">
                    <a href="{% url 'signup profile' %}">
                        Sign up
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/posts/add-photo.html
{% extends 'shared/site.html' %}
{% block site_content %}

<h1 class="text-center">Add photo</h1>
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <form method="post" class="furniture-form" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button class="button btn btn-primary mt-2" type="submit">Create</button>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

{% endblock %}

templates/posts/comment-page.html
{% extends 'shared/site.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy form form.helper %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/comment-page.css' %}">
{% endblock %}


{% block site_content %}

    <h1>Comments and Details</h1>
        <div class="d-block" style="background-color: rgb(230, 240, 240); padding:2%">
            <div class="box">
                <form method="post">
                    {{ form }}
                    {% csrf_token %}
                    <button class="button btn btn-primary mt-2" type="submit">Add comment</button>
                </form>
            </div>
            <br/><br/>
            {% if post.comment_set.count > 0 %}
                {% for comment in post.comment_set.all %}
                    <div class="box">
                        <h5><em>{{ comment.comment }}</em></h5>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <div class="box">
                    <h3>No comments yet...</h3>
                </div>
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/posts/feed.html
{% extends 'shared/site.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/feed.css' %}">
{% endblock %}

{% block site_content %}
    <h1 class="list-feed-h1">Home Feed</h1>
    <ul class="list-horizontal list-feed">
        {% for post in posts %}
            <li class="list-item">
                <div class="post-details">
                    <p class="post-info"><img src="/static/pin.png"
                                              alt="image of {{ post.location }}"> {{ post.location }}</p>
                    <p class="post-description">{{ post.user.user.username }}: {{ post.description }}</p>
                    <div class="post-buttons">
                    {% if user.id != post.user.user.id %}
                        <a href="{% url 'post like' post.pk %}"><img src="/static/heart.png"></a>
                    {% endif %}
                        Likes: {{ post.like_set.count }}
                        <a href="{% url 'post comments' post.pk %}" class="button btn btn-primary">Comments</a>
                        {% if user.id == post.user.user.id %}
                            <a href="{% url 'post edit' post.pk %}" class="button btn btn-success">Edit</a>
                            <a href="{% url 'post delete' post.pk %}"
                               class="button-danger btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
                <img src="{{ post.image.url }}" alt="image of {{ post.location }}">
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/posts/post-delete.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete this post?</h1>
            <h2>WARNING! All the information about this post will be deleted.</h2>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'post delete' post.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-danger">Confirm</button>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/post-edit.html
{% extends 'shared/site.html' %}
{% block site_content %}

    <h1 class="text-center">Edit</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'post edit' post.pk %}" class="furniture-form">
                {{ form.as_p }}
                {% csrf_token %}
                <button class="button btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

templates/shared/site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block site_title %}Adventr{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/clear.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
{% include 'partials/nav.html' %}
<div id="root">
    {% block site_content %}
        Adventr
    {% endblock %}
{#</div>#}
{##}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"#}
{#        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"#}
{#        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"#}
{#        crossorigin="anonymous"></script>#}
{##}
{#</body>#}
{#</html>#}